DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS topic CASCADE;
DROP TABLE IF EXISTS discussion CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS topic_tag CASCADE;